const file = 'districts.json';

const alipsa = {
  Pune: '10050',
  Bardhaman: '7977',
  'Bangalore Urban': '7001',
  Salem: '5954',
  'East Godavari': '5867',
  'Ranga Reddy': '1',
  Kanchipuram: '5790',
  Thane: '5511',
  Viluppuram: '5374',
  Ahmedabad: '5308',
  Guntur: '5237',
  Tiruvallur: '4996',
  'West Godavari': '4780',
  Nashik: '4666',
  Belagavi: '4653',
  'North 24 Parganas': '4592',
  Chittoor: '4571',
  Vellore: '4499',
  Hooghly: '4420',
  Satara: '4332',
  Ahmednagar: '4198',
  Erode: '4184',
  Karimnagar: '4170',
  'West Medinipur': '4096',
  Rajkot: '3928',
  Krishna: '3913',
  Tiruvannamalai: '3832',
  Tumkur: '3805',
  Cuddalore: '3747',
  Bankura: '3711',
  Birbhum: '3668',
  Cuttack: '3553',
  Prakasam: '3535',
  Vishakhapatnam: '3530',
  Bhavnagar: '3486',
  Jaipur: '3454',
  Kolhapur: '3398',
  Coimbatore: '3366',
  Aurangabad: '3364',
  'Mumbai Suburban': '3295',
  Khordha: '3278',
  Kutch: '3267',
  'South 24 Parganas': '3245',
  Howrah: '3243',
  Nagpur: '3221',
  Kolkata: '3208',
  'Purba Medinipur': '1',
  Tiruchirappalli: '3090',
  Mehsana: '3089',
  Nellore: '3077',
  Raigad: '3069',
  Anantapuram: '3055',
  Murshidabad: '3040',
  Patna: '3037',
  Jalgaon: '2976',
  Thrissur: '2971',
  Ganjam: '2947',
  Solapur: '2908',
  Madurai: '2838',
  Tirunelveli: '2831',
  Namakkal: '2812',
  Nalgonda: '2776',
  Sangli: '2759',
  Kadapa: '2748',
  Nadia: '2746',
  Tiruppur: '2738',
  Medak: '2734',
  Banaskantha: '2726',
  Warangal: '2675',
  Nizamabad: '2618',
  'Dakshina Kannada': '2587',
  Dhanbad: '2556',
  Udupi: '2515',
  Surat: '2489',
  Srikakulam: '2470',
  Kurnool: '2449',
  Mahabubnagar: '2372',
  Mandya: '2370',
  Virudhunagar: '2367',
  Gulbarga: '2343',
  Jalore: '2318',
  Varanasi: '2294',
  Bhilwara: '2283',
  'Uttara Kannada': '2281',
  Dindigul: '2270',
  Udaipur: '2252',
  Chennai: '2252',
  Pali: '2251',
  Mysuru: '2243',
  Jajpur: '2202',
  Alappuzha: '2192',
  Jodhpur: '2182',
  Nagaur: '2178',
  Dharmapuri: '2175',
  Kollam: '2166',
  Vadodara: '2160',
  Shivamogga: '2160',
  Indore: '2154',
  Kendrapara: '2146',
  Purulia: '2081',
  Bellary: '2078',
  Thiruvananthapuram: '2077',
  Ratnagiri: '2063',
  Junagadh: '2050',
  Dharwad: '2043',
  Ernakulam: '2030',
  Kozhikode: '2015',
  'Bangalore Rural': '2010',
  Bokaro: '2009',
  Raipur: '1993',
  Palakkad: '1985',
  Anand: '101972050',
  Jamnagar: '1961',
  Sivaganga: '1949',
  Puri: '1903',
  Amravati: '1897',
  Davanagere: '1878',
  Balasore: '1870',
  Hassan: '1866',
  Lucknow: '1852',
  Amreli: '1844',
  Krishnagiri: '1835',
  Patan: '1825',
  Surendranagar: '1809',
  Gandhinagar: '1773',
  Khammam: '1768',
  Bagalkot: '1728',
  Hyderabad: '1723',
  Sindhudurg: '1708',
  Ranchi: '1698',
  Nalanda: '1697',
  Chikkamagaluru: '1695',
  Chitradurga: '1690',
  'Kanpur Nagar': '1630',
  Bhagalpur: '1620',
  Kasaragod: '1617',
  Bijapur: '1582',
  Bhopal: '1581',
  Kolar: '1574',
  Buldhana: '1551',
  Latur: '1542',
  Beed: '1531',
  Adilabad: '1517',
  Kannur: '1507',
  Kota: '1497',
  Vizianagaram: '1495',
  Jagatsinghpur: '1494',
  Ajmer: '1492',
  Ramanagara: '1489',
  Haveri: '1484',
  Durg: '1478',
  Sikar: '1474',
  Kottayam: '1466',
  Jhunjhunu: '1463',
  Rohtas: '1439',
  Malda: '1432',
  Ramanathapuram: '1396',
  Allahabad: '1395',
  Khargone: '1386',
  Begusarai: '1381',
  Nanded: '1366',
  'North Goa': '1358',
  Bhadrak: '1338',
  Raichur: '1336',
  Bhojpur: '1333',
  Sirohi: '1327',
  Bikaner: '1314',
  Bilaspur: '1306',
  Gaya: '1303',
  Karur: '1294',
  Bidar: '1292',
  Sabarkatha: '1275',
  Pudukkottai: '1273',
  Alwar: '1250',
  Ghaziabad: '1222',
  Dhule: '1208',
  Ghazipur: '1184',
  'North West Delhi': '1171',
  Sagar: '1170',
  Churu: '1166',
  Rajsamand: '1166',
  Agra: '1165',
  Ujjain: '1163',
  Navsari: '1158',
  Akola: '1145',
  Bagmati: '1143',
  Jhansi: '1133',
  Mathura: '1126',
  Chikballapur: '1124',
  Giridih: '1109',
  Barmer: '1105',
  Kheda: '1101',
  Samastipur: '1097',
  Parbhani: '1095',
  Thoothukkudi: '1094',
  Munger: '1084',
  Chittaurgarh: '1081',
  Valsad: '1065',
  Mirzapur: '1062',
  Prayagraj: '1050',
  Yavatmal: '1047',
  'East Singhbhum': '1041',
  Osmanabad: '1035',
  Malappuram: '1035',
  Dhar: '1024',
  Jaunpur: '1012',
  Kamrup: '1011',
  Mandsaur: '993',
  Jalna: '988',
  Theni: '977',
  Nagapattinam: '973',
  Nayagarh: '970',
  Meerut: '964',
  Madhubani: '961',
  Aligarh: '957',
  Pondicherry: '950',
  Saran: '948',
  Mandi: '944',
  Perambalur: '933',
  Kangra: '930',
  Gorakhpur: '920',
  Jabalpur: '913',
  Deoghar: '908',
  Chandauli: '908',
  Chhindwara: '890',
  Bhiwani: '887',
  Bargarh: '883',
  Chamarajanagar: '882',
  Dhenkanal: '880',
  Buxar: '873',
  Wardha: '865',
  'Janjgir-Champa': '863',
  Gurgaon: '863',
  Pathanamthitta: '858',
  Kendujhar: '852',
  Mumbai: '850',
  Ballia: '845',
  Bundi: '840',
  Koppal: '840',
  Angul: '832',
  Gadag: '821',
  Sundargarh: '814',
  Chandrapur: '813',
  Pratapgarh: '799',
  Siwan: '789',
  Muzaffarpur: '788',
  Rajgarh: '786',
  Hisar: '786',
  Bharuch: '780',
  'South West Delhi': '780',
  Dewas: '779',
  Gwalior: '778',
  Palghar: '774',
  Morbi: '773',
  Betul: '773',
  Ratlam: '773',
  Darbhanga: '772',
  Dehradun: '754',
  Porbandar: '741',
  'Sant Ravidas Nagar': '730',
  Sambalpur: '712',
  'West Delhi': '710',
  Ariyalur: '709',
  Mayurbhanj: '700',
  Vaishali: '687',
  Katihar: '685',
  Washim: '681',
  Jalandhar: '671',
  Hanumangarh: '667',
  Ludhiana: '667',
  Dausa: '666',
  Ganganagar: '659',
  'Gautam Buddh Nagar': '659',
  Baran: '656',
  Bareilly: '656',
  'South Delhi': '652',
  Neemuch: '651',
  Nilgiris: '643',
  Jalpaiguri: '635',
  Faridabad: '629',
  'Sawai Madhopur': '616',
  Jharsuguda: '615',
  Jind: '610',
  Jehanabad: '610',
  Raigarh: '603',
  Sonepat: '601',
  'Uttar Dinajpur': '600',
  Deoria: '597',
  Ramgarh: '595',
  Lakhisarai: '594',
  Tonk: '591',
  Satna: '590',
  Haridwar: '589',
  Banka: '585',
  Palamu: '582',
  Jhalawar: '581',
  Azamgarh: '574',
  Raisen: '568',
  Rewa: '566',
  Nawada: '562',
  Dungarpur: '561',
  Kalahandi: '561',
  Sehore: '558',
  Rewari: '555',
  Shimla: '555',
  Kodagu: '555',
  Khagaria: '555',
  Chittagong: '554',
  Karauli: '548',
  Bharatpur: '546',
  Hingoli: '542',
  Nandurbar: '530',
  Kaimur: '528',
  'Purvi Champaran': '527',
  Lumbini: '526',
  Idukki: '524',
  Panchmahal: '524',
  Bakod: '522',
  Saharanpur: '520',
  Thanjavur: '516',
  Damoh: '515',
  Mahendragarh: '514',
  Balangir: '513',
  Hoshangabad: '507',
  Khandwa: '502',
  Hamirpur: '497',
  Gopalganj: '495',
  Muzaffarnagar: '491',
  Narsinghpur: '490',
  Jhajjar: '489',
  Shajapur: '487',
  Bulandshahar: '485',
  'Devbhoomi Dwarka': '484',
  Karnal: '481',
  'South Goa': '478',
  Darjeeling: '477',
  Ambala: '475',
  'East Delhi': '475',
  Patiala: '468',
  Seoni: '466',
  Jamui: '465',
  Rohtak: '458',
  Vidisha: '457',
  'Kamrup Metropolitan': '455',
  Tikamgarh: '452',
  Arwal: '452',
  Banswara: '447',
  Wayanad: '446',
  Rajnandgaon: '442',
  Narayani: '440',
  Sirsa: '440',
  Yamunanagar: '437',
  Moradabad: '435',
  Dumka: '434',
  Cachar: '431',
  Gandaki: '427',
  Shivpuri: '424',
  Bhandara: '424',
  Hoshiarpur: '421',
  Kullu: '412',
  Nainital: '410',
  Purnia: '403',
  Katni: '399',
  Jalaun: '398',
  Bengaluru: '398',
  Koderma: '395',
  Koshi: '394',
  'Dakshin Dinajpur': '393',
  Una: '387',
  Chhatarpur: '387',
  'North East Delhi': '385',
  Yadgir: '384',
  Kurukshetra: '379',
  Kushinagar: '374',
  Korba: '373',
  Sitamarhi: '372',
  Koraput: '370',
  'New Delhi': '366',
  Almora: '366',
  Jamtara: '366',
  Panipat: '364',
  'Seraikela Kharsawan': '363',
  Gondia: '361',
  Bijnor: '361',
  Mau: '361',
  Sheikhpura: '360',
  Unnao: '357',
  Saharsa: '356',
  Nagaon: '356',
  Balaghat: '353',
  Dahod: '353',
  'Pashchim Champaran': '351',
  Solan: '348',
  Supaul: '347',
  Guna: '346',
  'West Tripura': '341',
  Fatehabad: '341',
  'North Delhi': '336',
  'Cooch Behar': '334',
  Mahasamund: '332',
  Bhind: '328',
  Panchkula: '326',
  Darrang: '326',
  Jaisalmer: '319',
  Bagpat: '315',
  Kaithal: '314',
  Dhaka: '314',
  Godda: '313',
  'Rae Bareli': '310',
  Barwani: '308',
  'Ambedkar Nagar': '307',
  Ayodhya: '304',
  Sultanpur: '301',
  Kawardha: '299',
  Hardoi: '294',
  Janakpur: '291',
  'Pauri Garhwal': '290',
  Sitapur: '290',
  Dhamtari: '288',
  Rayagada: '286',
  Aravalli: '285',
  Subarnapur: '284',
  Sonbhadra: '283',
  'Sahibzada Ajit Singh Nagar': '282',
  Etah: '281',
  Tapi: '281',
  'Udham Singh Nagar': '280',
  Harda: '268',
  Sangrur: '267',
  Auraiya: '262',
  Garhwa: '260',
  Shamli: '260',
  Fatehpur: '249',
  Shahdol: '249',
  Palwal: '249',
  Banda: '247',
  'Lakhimpur Kheri': '247',
  Surguja: '246',
  Firozabad: '245',
  Narmada: '240',
  Mechi: '236',
  Khulna: '236',
  Basti: '234',
  Amritsar: '234',
  Hathras: '233',
  Bongaigaon: '232',
  Chandigarh: '232',
  Sahibganj: '232',
  Lalitpur: '231',
  Gonda: '231',
  Kaushambi: '230',
  Panna: '230',
  Etawah: '228',
  Morena: '225',
  Chitrakoot: '224',
  Dhubri: '222',
  Siddharthnagar: '220',
  Maharajganj: '218',
  Mainpuri: '216',
  Burhanpur: '215',
  Mahoba: '215',
  Araria: '215',
  Bathinda: '214',
  'Central Delhi': '214',
  Chamba: '213',
  Tinsukia: '212',
  Barabanki: '212',
  Ashoknagar: '211',
  Madhepura: '210',
  Gadchiroli: '209',
  Sonitpur: '208',
  Badaun: '208',
  Kokrajhar: '205',
  Shahjahanpur: '205',
  Jhabua: '205',
  'Kanpur Dehat': '203',
  Gajapati: '200',
  Rupnagar: '198',
  Barpeta: '196',
  Balod: '195',
  'West Singhbhum': '193',
  Sirmaur: '193',
  Singrauli: '192',
  Satkhira: '189',
  Nabarangpur: '188',
  'Tehri Garhwal': '187',
  Nalbari: '184',
  Sagarmatha: '179',
  Chatra: '178',
  Pithoragarh: '177',
  Pathankot: '177',
  Anuppur: '175',
  'Imphal West': '174',
  Datia: '174',
  Dhaulpur: '174',
  Mandla: '173',
  Gurdaspur: '173',
  Kannauj: '172',
  'South East Delhi': '172',
  Sidhi: '168',
  Chamoli: '162',
  Koriya: '161',
  Umaria: '161',
  Mewat: '157',
  Agar: '157',
  Bametara: '154',
  Fazilka: '152',
  'Sant Kabir Nagar': '151',
  Bastar: '151',
  Mahisagar: '150',
  Balrampur: '146',
  'Baloda Bazar': '142',
  Karimganj: '141',
  Tangail: '138',
  Farrukhabad: '137',
  Jammu: '135',
  Dhawalagiri: '134',
  Bahraich: '133',
  Comilla: '133',
  'Shahid Bhagat Singh Nagar': '132',
  Jessore: '131',
  Bogra: '130',
  Dibrugarh: '129',
  Kapurthala: '129',
  Jorhat: '127',
  Mymensingh: '127',
  'Karbi Anglong': '124',
  Bageshwar: '124',
  Rampur: '124',
  Rudraprayag: '124',
  Uttarkashi: '120',
  Mahakali: '119',
  Nuapada: '119',
  'Chhota Udaipur': '118',
  Amroha: '117',
  Sivasagar: '116',
  Latehar: '116',
  Kandhamal: '116',
  Hailakandi: '115',
  'South Tripura': '114',
  Amethi: '114',
  'North Tripura': '113',
  'Moulvi Bazar': '113',
  Kanker: '113',
  Pakur: '112',
  Seti: '111',
  Gumla: '111',
  Goalpara: '110',
  Kishanganj: '110',
  'Imphal East': '109',
  Narayanganj: '108',
  Moga: '108',
  Pilibhit: '105',
  Sheopur: '101',
  Jashpur: '99',
  Pabna: '98',
  Bangalore: '96',
  'Dadra and Nagar Haveli': '96',
  Mansa: '93',
  Boudh: '93',
  Shahdara: '92',
  Malkangiri: '92',
  Barisal: '91',
  Morigaon: '91',
  Dinajpur: '90',
  Gazipur: '90',
  Lakhimpur: '89',
  Daman: '88',
  Habiganj: '88',
  Kondagaon: '87',
  Rapti: '86',
  Surajpur: '85',
  Bheri: '85',
  Champawat: '82',
  Brahmanbaria: '82',
  Mungeli: '2',
  Rajshahi: '79',
  Bagerhat: '78',
  Kushtia: '77',
  Sambhal: '76',
  Natore: '75',
  Gopalganj: '2',
  'Sri Muktsar Sahib': '74',
  Naogaon: '73',
  'Dima Hasao': '73',
  Manikganj: '72',
  Dhemaji: '72',
  Jhenaidah: '72',
  Munshiganj: '71',
  Narail: '71',
  Dindori: '70',
  Sirajganj: '69',
  Shrawasti: '68',
  Feni: '67',
  Dantewada: '67',
  Sunamganj: '63',
  Kishoreganj: '63',
  'Kanshi Ram Nagar': '61',
  Bishnupur: '60',
  Sylhet: '60',
  Kathua: '58',
  Faridpur: '60',
  Noakhali: '60',
  'East Khasi Hills': '58',
  Narsingdi: '57',
  Khunti: '56',
  Ferozepur: '55',
  'Gir Somnath': '55',
  "Cox's Bazar District": '54',
  Alirajpur: '53',
  Netrokona: '52',
  'East Sikkim': '52',
  Chandpur: '52',
  Deogarh: '51',
  'West Garo Hills': '51',
  Yanam: '50',
  Khagrachari: '50',
  Pithoragharh: '50',
  Madaripur: '50',
  Rajbari: '49',
  Rangpur: '49',
  'Fatehgarh Sahib': '48',
  'Sahibazada Ajit Singh Nagar': '48',
  Barnala: '47',
  Jaipurhat: '47',
  Magura: '46',
  Hapur: '46',
  Dang: '44',
  Dhalai: '44',
  Gariaband: '42',
  Faridkot: '42',
  Thakurgaon: '40',
  Gaibandha: '40',
  Sipahijala: '39',
  Samba: '39',
  'Sri Amarajeevi Potti Sri Ramulu Nellore': '38',
  Udhampur: '38',
  Thoubal: '38',
  'Tarn Taran': '37',
  'Gautam Buddha Nagar': '36',
  Jamalpur: '35',
  Pirojpur: '35',
  Thiruvarur: '34',
  Lalmonirhat: '33',
  Chirang: '33',
  Patuakhali: '33',
  Sherpur: '33',
  Mandalay: '32',
  Simdega: '32',
  Lakshmipur: '30',
  Chapainawabganj: '29',
  Senapati: '29',
  Sheohar: '29',
  Tharparkar: '29',
  Alipurduar: '28',
  Chamarajnagar: '27',
  Gomati: '27',
  Srinagar: '26',
  Mandal: '4',
  Barguna: '25',
  'South Sikkim': '24',
  Baksa: '23',
  Kurigram: '23',
  'Delhi (district)': '22',
  Chuadanga: '22',
  Shariatpur: '21',
  Firozpur: '21',
  Amrawati: '21',
  'Lahaul And Spiti': '21',
  Nilphamari: '21',
  Dimapur: '20',
  'Papum Pare': '20',
  'Rangamati Hill': '20',
  'Bengaluru Rural': '20',
  Udalguri: '19',
  'Pyin Oo Lwin': '19',
  'Purba Bardhaman': '1',
  'Nyaung-U': '19',
  Kanyakumari: '19',
  Doda: '18',
  Bulandshahr: '17',
  Khowai: '17',
  Ghotki: '17',
  Karnali: '16',
  Aizawl: '15',
  Medinipur: '15',
  Sanghar: '15',
  Unakoti: '15',
  Panchagarh: '13',
  Golaghat: '13',
  Reasi: '13',
  Jhalokati: '12',
  Jacobabad: '12',
  'Mumbai City': '12',
  'Ri-Bhoi': '12',
  Leh: '11',
  'Khandwa (East Nimar)': '11',
  Bandarban: '11',
  Rajouri: '10',
  Tharparkar: '10',
  Kinnaur: '10',
  'West Sikkim': '10',
  Puttalam: '9',
  Delhi: '9',
  Tiruppur: '9',
  Anantnag: '9',
  Kashmore: '9',
  Lahore: '9',
  Mahbubnagar: '9',
  Lohit: '8',
  Rangareddy: '8',
  Mirpur: '8',
  Churachandpur: '8',
  Tuticorin: '8',
  Umerkot: '8',
  Kishtwar: '8',
  Taluk: '8',
  Taluka: '8',
  Sialkot: '7',
  Chandel: '7',
  Kurunegala: '7',
  Larkana: '6',
  Lunglei: '6',
  Wokha: '6',
  Kupwara: '6',
  Baramulla: '6',
  Kohima: '6',
  Meherpur: '6',
  Tirupur: '5',
  Umerkot: '5',
  Multan: '5',
  Sukkur: '5',
  Morbi: '5',
  'Sundargarh (Sundergarh)': '5',
  Khairpur: '5',
  Jhenidah: '5',
  Kolasib: '5',
  Ramban: '5',
  Bhola: '5',
  'North Garo Hills': '5',
  Midnapore: '5',
  Tiruchirappalli: '5',
  Pulwama: '4',
  'West Kameng': '4',
  Puducherry: '4',
  Khanewal: '4',
  'Paschim Bardhaman': '4',
  Mahabubabad: '4',
  Lawngtlai: '4',
  Mokokchung: '4',
  Thatta: '4',
  Narayanpur: '4',
  Kanpur: '4',
  'Taran Taran': '4',
  Poonch: '4',
  Narowal: '3',
  Jajapur: '3',
  'Nawan Shehar': '3',
  'Khargone (West Nimar)': '3',
  Kyaukme: '3',
  Belgaum: '3',
  Karaikal: '3',
  Sewapuri: '3',
  Krishnagiri: '3',
  'Baleswar (Balasore)': '3',
  Shikarpur: '3',
  Gram: '3',
  Feni: '3',
  'Dera Ghazi Khan': '3',
  Ukhrul: '3',
  Hazaribag: '3',
  Anuradhapura: '3',
  Anantapur: '3',
  Coimbatore: '3',
  Ganderbal: '3',
  Jamshoro: '3',
  Malapuram: '3',
  Kolaghat: '3',
  Manshera: '3',
  'West Jaintia Hills': '3',
  Jafarabad: '3',
  Jalpaguri: '3',
  Madhali: '2',
  Buldana: '2',
  'Noushahro Feroze': '2',
  Mahe: '2',
  Bulacan: '2',
  'PURBA BARDHAMAN': '2',
  Arisinakunte: '2',
  Muzaffargarh: '2',
  Borgoanv: '2',
  Dharwad: '2',
  'Mirpur Khas': '2',
  'Bolangir (Balangir)': '2',
  Jhelum: '2',
  Tirap: '2',
  'North Sikkim': '2',
  Juhnjhunun: '2',
  Hanumanpur: '2',
  Sukma: '2',
  Midjil: '2',
  Magadh: '2',
  Thiruvarur: '2',
  Chittoor: '2',
  Rawalpindi: '2',
  Chittorgarh: '2',
  Vehari: '2',
  Sivaru: '2',
  Thatta: '2',
  Kalan: '2',
  Medchal: '2',
  Telangana: '2',
  Bandipora: '2',
  Taunggyi: '2',
  'Rahim Yar Khan': '2',
  'Bargarh (Baragarh)': '2',
  Kyaukse: '2',
  'East Nimar': '2',
  Kargil: '2',
  Manki: '2',
  'Purba Singhbhum': '2',
  'Tando Allahyar': '2',
  Banki: '2',
  'East Jaintia Hills': '2',
  Yadadri: '2',
  Khurd: '2',
  Layyah: '2',
  Chhattisgarh: '2',
  Badin: '2',
  Sahi: '2',
  Modidih: '2',
  Cheruvu: '2',
  Tuensang: '2',
  Bahawalpur: '2',
  Chikkaballapur: '1',
  Raghunathpally: '1',
  Kullaveeram: '1',
  Kabirdham: '1',
  Khunkhunia: '1',
  Kalaburgi: '1',
  Jyotkalyan: '1',
  Kalmichabar: '1',
  Kalyachawal: '1',
  Jodhpur: '1',
  Jhunjhunun: '1',
  Kankadahad: '1',
  Jhargram: '1',
  Jas: '1',
  Kasur: '1',
  Jamshedpur: '1',
  Jammu: '1',
  Kavalu: '1',
  Kayangulam: '1',
  Jamie: '1',
  Kenduar: '1',
  Jambhale: '1',
  'Kendujhar (Keonjhar)': '1',
  Kere: '1',
  Khamman: '1',
  Jahatshinpur: '1',
  Khliapali: '1',
  Jahanabad: '1',
  Jagitial: '1',
  Jagdishpur: '1',
  Kodarwadi: '1',
  Koilighughar: '1',
  Itharajpally: '1',
  'Ira Dakshina Kannada': '1',
  'Indas West': '1',
  Kome: '1',
  Hosahatti: '1',
  'Hathatganj Bazar': '1',
  Kottal: '1',
  Kottala: '1',
  Haripal: '1',
  'Krishna Goundanputhur': '1',
  Kuberpur: '1',
  Kulasahi: '1',
  Kulgam: '1',
  Hamlet: '1',
  Guwahati: '1',
  Guthu: '1',
  Gundareddipalli: '1',
  Lodhran: '1',
  Lokhimondir: '1',
  'Lower Dibang Valley': '1',
  Gudiyattam: '1',
  Madhab: '1',
  Madhala: '1',
  Madhuranthgam: '1',
  Mahishpara: '1',
  Ghoshkhali: '1',
  Majhpara: '1',
  Ghausa: '1',
  Mallapuram: '1',
  Gazipur: '1',
  Gavthanwadi: '1',
  Manfls: '1',
  Manjuri: '1',
  Matale: '1',
  Matiari: '1',
  Gurappanapalya: '1',
  Mavelikara: '1',
  Mayiladuthurai: '1',
  Gajrabhra: '1',
  Mindat: '1',
  Mohnyin: '1',
  Moriys: '1',
  Moubhandar: '1',
  Munsefdanga: '1',
  Myingyan: '1',
  Kolak: '1',
  Mysore: '1',
  Faisalabad: '1',
  'NALLUGUTONA THANDA': '1',
  NAMOPARA: '1',
  'NISARTA FALIYU': '1',
  FARIYO: '1',
  'Eruthappanpatty, Achanampatty': '1',
  Nadurbar: '1',
  Ersama: '1',
  Nagapatinam: '1',
  Erode: '1',
  Ernakulam: '1',
  Nagpur: '1',
  Namegiripettai: '1',
  'East Garo Hills': '1',
  'Nankana Sahib': '1',
  Narayanganj: '1',
  'East Burdhaman': '1',
  Narottambati: '1',
  Dungarpad: '1',
  Nathshahi: '1',
  Dundibar: '1',
  Nawanshahar: '1',
  Dosautuni: '1',
  Nayapara: '1',
  Donde: '1',
  Neemuh: '1',
  Diviseema: '1',
  Nimaichandpur: '1',
  Nisampattu: '1',
  Nowbhanga: '1',
  Nuagan: '1',
  ONDA: '1',
  'District Hyderabad': '1',
  Palayam: '1',
  Dinnuru: '1',
  Panchamahal: '1',
  Panchla: '1',
  Parsatand: '1',
  Dharawad: '1',
  Dhananjayapur: '1',
  Patunia: '1',
  Peddapalli: '1',
  Peringottukkara: '1',
  Phek: '1',
  Pimplod: '1',
  'Devchand Nagar': '1',
  Polonnaruwa: '1',
  Devarahalli: '1',
  Deopara: '1',
  Prakasamdt: '1',
  Punanga: '1',
  Purandar: '1',
  Dehgam: '1',
  Davanagere: '1',
  Daudnangar: '1',
  Darwaja: '1',
  Puudur: '1',
  Dangle: '1',
  Dakshinpara: '1',
  Dabormore: '1',
  Coupati: '1',
  'Rajshahi Division': '1',
  Ramanathapuram: '1',
  Ramannavuru: '1',
  Rameswar: '1',
  Chovisha: '1',
  Chikmagalur: '1',
  Rmalenka: '1',
  Chikkamanchal: '1',
  Chikkamagaluru: '1',
  Chikkaballapura: '1',
  'Sabroom South': '1',
  Chickballapura: '1',
  Chhaka: '1',
  Chhappartand: '1',
  Sahiwal: '1',
  Saiha: '1',
  Salamakalhally: '1',
  Cheruve: '1',
  Cheriyakkara: '1',
  Charanpur: '1',
  Saraswati: '1',
  Sarpsborg: '1',
  Champhai: '1',
  Satkhira: '1',
  Chakala: '1',
  Sayalkudi: '1',
  Searsole: '1',
  CHHAKA: '1',
  Bramhagiri: '1',
  Sheikhupura: '1',
  Shendage: '1',
  'Birgunj Sub Metro': '1',
  Sillod: '1',
  Biramarajpur: '1',
  Bhola: '1',
  Bhatradi: '1',
  Sitapokhari: '1',
  Bharuch: '1',
  Bharadiya: '1',
  Sivagangai: '1',
  Bhamo: '1',
  Benazirabad: '1',
  Bellary: '1',
  Sonipat: '1',
  Belgaum: '1',
  Sorpu: '1',
  'South Chiruvolulanka': '1',
  Batticaloa: '1',
  'South West Khasi Hills': '1',
  'South, Balasore': '1',
  'Sri Kalahasti': '1',
  'Sri Potti Sriramulu Nellore': '1',
  'Barishal Division': '1',
  'St Kabir Nagar': '1',
  'St Ravidas Nagar': '1',
  Sukshetra: '1',
  Baramusapur: '1',
  Bankikodla: '1',
  Surhan: '1',
  Swabia: '1',
  Sylhet: '1',
  'Sylhet Division': '1',
  TAVALLI: '1',
  Tagaria: '1',
  Tal: '1',
  Taljhari: '1',
  'Taluk Kanjirangulam': '1',
  Taluku: '1',
  Tamenglong: '1',
  Targoan: '1',
  Thadakaleru: '1',
  'Banas Kantha': '1',
  'Tando Muhammad Khan': '1',
  Thilakkal: '1',
  Thirumalapura: '1',
  Balur: '1',
  Thiruvattoor: '1',
  Thiruvallur: '1',
  Thokkottu: '1',
  Balubele: '1',
  Thottiyam: '1',
  Tikrapada: '1',
  Tirth: '1',
  Baleshwar: '1',
  Balakrouth: '1',
  Bajar: '1',
  Tiruvanamalai: '1',
  Tiruvellire: '1',
  Tola: '1',
  Totagalu: '1',
  Tumkur: '1',
  Badudevpur: '1',
  Udupi: '1',
  Badhe: '1',
  Ukaura: '1',
  Assonora: '1',
  'Ashok Nagar': '1',
  Arasuvayal: '1',
  Apalika: '1',
  Vadodara: '1',
  Vankdi: '1',
  Vanur: '1',
  Veniveerapur: '1',
  Vill: '1',
  Virdi: '1',
  Visakhapatnam: '1',
  'Amani Kere': '1',
  Alamaram: '1',
  'Ahra Dera': '1',
  Agarpada: '1',
  'West Siang': '1',
  Abbottabad: '1',
  Abaganga: '1',
  Yellamma: '1',
  Zamin: '1',
  Achra: '1',
  'Agragaram, Andananallur': '1',
};

const shortForms = {
  'Andaman and Nicobar Islands': 'AN',
  'Andhra Pradesh': 'AP',
  'Arunachal Pradesh': 'AR',
  Assam: 'AS',
  Bihar: 'BR',
  Chandigarh: 'CH',
  Chhattisgarh: 'CT',
  Delhi: 'DL',
  'Dadra & Nagar Haveli': 'DN',
  'Daman & Diu': 'DI',
  Goa: 'GA',
  Gujarat: 'GJ',
  'Himachal Pradesh': 'HP',
  Haryana: 'HR',
  Jharkhand: 'JH',
  'Jammu and Kashmir': 'JK',
  Karnataka: 'KA',
  Kerala: 'KL',
  Ladakh: 'LA',
  Maharashtra: 'MH',
  Meghalaya: 'ML',
  Manipur: 'MN',
  'Madhya Pradesh': 'MP',
  Mizoram: 'MZ',
  Nagaland: 'NL',
  Odisha: 'OD',
  Punjab: 'PB',
  Puducherry: 'PY',
  Rajasthan: 'RJ',
  Sikkim: 'SK',
  Telangana: 'TG',
  'Tamil Nadu': 'TN',
  Tripura: 'TR',
  TT: 'TT',
  UN: 'UN',
  'Uttar Pradesh': 'UP',
  Uttarakhand: 'UT',
  'West Bengal': 'WB',
};

const colorCodes = {
  'Andhra Pradesh': '#e3aafc',
  'Arunachal Pradesh': '#fbabc1',
  Assam: '#f6f1b0',
  Bihar: '#b5e6f0',
  Chhattisgarh: '#fcdfb3',
  Delhi: '#e0e4c9',
  Goa: '#b8f7d8',
  Gujarat: '#b3e5f9',
  'Himachal Pradesh': '#d5ccfd',
  Haryana: '#e5bbb2',
  Jharkhand: '#f8a0a2',
  'Jammu and Kashmir': '#fdbde9',
  Karnataka: '#fc9da6',
  Kerala: '#a9f2ae',
  Ladakh: '#d4dbf8',
  Maharashtra: '#feedb3',
  Meghalaya: '#e5f3af',
  Manipur: '#bfb9f5',
  'Madhya Pradesh': '#d5dfd4',
  Mizoram: '#fbd9bb',
  Nagaland: '#c7fee8',
  Odisha: '#c7f4e4',
  Punjab: '#e3fa93',
  Rajasthan: '#dcdfee',
  Sikkim: '#c6f2fb',
  Telangana: '#dee3f2',
  'Tamil Nadu': '#cfcdee',
  Tripura: '#fef1c7',
  'Uttar Pradesh': '#fdd7d7',
  Uttarakhand: '#eddce2',
  'West Bengal': '#dfc8be',
};

let yrnow = 0;
let inc = 0.04;

function map(n, start1, stop1, start2, stop2) {
  return ((n - start1) / (stop1 - start1)) * (stop2 - start2) + start2;
}

function constrain(n, low, high) {
  return Math.max(Math.min(n, high), low);
}

var colors = d3
  .scaleLinear()
  .domain(d3.ticks(0, 20, 7))
  .range([
    '#fff',
    '#FFFFBF',
    '#FEE08B',
    '#FDAE61',
    '#F46D43',
    '#D53E4F',
    '#9E0142',
  ]);

var pathLine = d3
  .line()

  .x(function (d) {
    return projection([d[0], d[1]])[0];
  })
  .y(function (d) {
    return projection([d[0], d[1]])[1];
  })
  .curve(d3.curveBasis);

function drawPaths() {
  for (let roar of zathura) {
    if (roar.name.includes('Andam')) continue;
    g.empty();
    g.append('path')
      .attr('d', pathLine(roar.points))
      .attr('class', 'twinkpath ' + roar.name)
      .style('stroke', '#0e0ec7cc')
      .style('fill', 'transparent')
      .style('stroke-width', '3px')
      .call(transition);
    // const total = path.node().getTotalLength();
    // console.log(total);
    break;
  }
}

function transition(path) {
  path.transition().duration(100000).attrTween('stroke-dasharray', tweenDash);
  // .on('end', function () {
  //   d3.select(this).call(transition);
  // });
}

function tweenDash() {
  var l = this.getTotalLength(),
    i = d3.interpolateString('0,' + l, l + ',' + l);
  return function (t) {
    return i(t);
  };
}

function animmate() {
  // window.abc = d3.selectAll('.twinkpath');
  // d3.selectAll('.twinkpath')
  //   .nodes[0].attr('stroke-dasharray', 100 + ' ' + 100)
  //   .attr('stroke-dashoffset', 100)
  //   .transition()
  //   .duration(5000)
  //   .ease('linear')
  //   .attr('stroke-dashoffset', 0);
  drawPaths();
}

function updateFacet() {
  let data = realData;
  drawSubUnits(data);
  drawPaths();
}

var width = window.innerWidth,
  height = window.innerHeight;

var projection = d3.geoMercator();

var path = d3.geoPath().projection(projection).pointRadius(2);
var neighbors = [];
var realData = null;

var svg = d3
  .select('#map')
  .append('svg')
  .attr('width', width)
  .attr('height', height);

var g = svg.append('g');

d3.json(file, function (error, data) {
  centerZoom(data);
  realData = data;
  neighbors = topojson.neighbors(data.objects.states.geometries);
  initiateNo();
});

function centerZoom(data) {
  var o = topojson.mesh(data, data.objects.states, function (a, b) {
    return a === b;
  });

  projection.scale(1).translate([0, 0]);

  var b = path.bounds(o),
    s =
      1 /
      Math.max(
        (b[1][0] - b[0][0]) / width,
        ((b[1][1] - b[0][1]) / height) * 1.04
      ),
    t = [
      (width - s * (b[1][0] + b[0][0])) * 0.41,
      (height - s * (b[1][1] + b[0][1])) * 0.5,
    ];

  var p = projection.scale(s).translate(t);

  return o;
}

function drawOuterBoundary(data) {
  const boundary = topojson.mesh(data, data.objects.states, function (a, b) {
    return a === b;
  });
  g.append('path')
    .datum(boundary)
    .attr('d', path)
    .attr('class', 'subunit-boundary')
    .attr('fill', 'none')
    .attr('stroke', '#3a403d');
}

function drawSubUnits(data) {
  var subunits = g
    .selectAll('.subunit')
    .data(topojson.feature(data, data.objects.districts).features)
    .enter()
    .append('path')
    .attr('class', 'subunit')
    .attr('d', path)
    .attr('fill', function (d) {
      if (!(d.properties.district in alipsa)) {
        console.log(d.properties.district);
      }
      return '#fff';
    })
    .style('stroke', function (d) {
      return '#ddd';
    })
    .style('stroke-width', function (d) {
      return path.area(d) > 3000 ? '1px' : '0.8px';
    });
  var subunits = g
    .selectAll('.subunitx')
    .data(topojson.feature(data, data.objects.states).features)
    .enter()
    .append('path')
    .attr('class', 'subunitx')
    .attr('fill', 'transparent')
    .attr('d', path)
    .style('stroke', function (d) {
      return '#222';
    })
    .style('stroke-width', function (d) {
      return '1px';
    });
  return subunits;
}

function drawSubUnitLabels(data) {
  g.selectAll('.subunit-label')
    .data(topojson.feature(data, data.objects.states).features)
    .enter()
    .append('text')
    .attr('class', 'subunit-label')
    .attr('transform', function (d) {
      const [locx, locy] = path.centroid(d);
      const fin = [locx, locy];
      return 'translate(' + fin + ')';
    })
    .attr('dy', '.35em')
    .attr('text-anchor', 'middle')
    .style('font-size', function (d) {
      const area = path.area(d);
      const [[left, top], [right, bottom]] = path.bounds(d);
      const wid = right - left;
      if (wid < 200) {
        const mappedf = map(wid, 20, 200, 0.2, 1);
        const confx = constrain(mappedf, 0.2, 1);
        return confx * 1.2 + 'em';
      } else {
        const mappedf = map(wid, 200, 2000, 1, 1.8);
        const confx = constrain(mappedf, 1, 1.8);
        return confx + 'em';
      }
    })
    .style('fill', (d) => '#222')
    .text(function (d) {
      return d.properties.st_nm in cases ? 'a' : d.properties.st_nm;
    });
}

function initiateNo() {
  updateFacet();
}
